version: '3.4'
x-thumbler: &thumbler
  environment:
    DB_URL: mongodb://mongodb/thumbler
  working_dir: /thumbler
  ports:
    - "7501:7501"
x-node: &node
  secrets:
    - id_rsa
  volumes:
    - type: bind
      source: .
      target: /thumbler
    - node_modules:/node_modules
    - cache:/usr/local/share/.cache
  dns:
    - 8.8.8.8
    - 8.8.4.4
x-from-latest: &from-latest
  image: thumbler:latest

services:
  thumbler:
    << : [*node, *thumbler]
    build: ./packages/docker
    command: yarn start
  shell:
    << : [*node, *thumbler, *from-latest]
    command: /bin/sh
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  cache:
  node_modules:
  data:
secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
