version: '3.4'

x-thumbler: &thumbler
  environment:
    DB_URL: mongodb://mongodb/thumbler
  ports:
    - "7501:7501"
x-node: &node
  image: thumbler:latest
  build:
    context: ./toggl/docker
    args:
      node_version: 10.14.0
      yarn_version: 1.12.1
  user: node
  secrets:
    - id_rsa
  volumes:
    - type: bind
      source: .
      target: /home/node/thumbler
    - cache:/usr/local/share/.cache
  dns:
    - 8.8.8.8
    - 8.8.4.4

services:
  thumbler:
    << : [*node, *thumbler]
    command: yarn start
    depends_on:
      - mongodb
  shell:
    << : [*node, *thumbler]
    command: /bin/sh
  mongodb:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  cache:
  node_modules:
  data:
secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
